# before python 3.6, the normal dict didn't guarantee the order
# and we had to use the ordered_dict. We don't have to use it anymore.